// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Test_State int32

const (
	Test_UNKNOWN  Test_State = 0
	Test_PASSED   Test_State = 1
	Test_FAILED   Test_State = 2
	Test_SKIPPED  Test_State = 3
	Test_PENDING  Test_State = 4
	Test_PANICKED Test_State = 5
	Test_TIMEDOUT Test_State = 6
	Test_INVALID  Test_State = 7
)

var Test_State_name = map[int32]string{
	0: "UNKNOWN",
	1: "PASSED",
	2: "FAILED",
	3: "SKIPPED",
	4: "PENDING",
	5: "PANICKED",
	6: "TIMEDOUT",
	7: "INVALID",
}
var Test_State_value = map[string]int32{
	"UNKNOWN":  0,
	"PASSED":   1,
	"FAILED":   2,
	"SKIPPED":  3,
	"PENDING":  4,
	"PANICKED": 5,
	"TIMEDOUT": 6,
	"INVALID":  7,
}

func (x Test_State) String() string {
	return proto.EnumName(Test_State_name, int32(x))
}
func (Test_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_3644d9311d3e1fc3, []int{2, 0}
}

type Report struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Commit               string   `protobuf:"bytes,3,opt,name=commit" json:"commit,omitempty"`
	Suites               []*Suite `protobuf:"bytes,4,rep,name=suites" json:"suites,omitempty"`
	StartedAt            int64    `protobuf:"varint,5,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	FinishedAt           int64    `protobuf:"varint,6,opt,name=finished_at,json=finishedAt" json:"finished_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3644d9311d3e1fc3, []int{0}
}
func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (dst *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(dst, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Report) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Report) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *Report) GetSuites() []*Suite {
	if m != nil {
		return m.Suites
	}
	return nil
}

func (m *Report) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *Report) GetFinishedAt() int64 {
	if m != nil {
		return m.FinishedAt
	}
	return 0
}

type Suite struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Tests                []*Test  `protobuf:"bytes,3,rep,name=tests" json:"tests,omitempty"`
	StartedAt            int64    `protobuf:"varint,4,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	FinishedAt           int64    `protobuf:"varint,5,opt,name=finished_at,json=finishedAt" json:"finished_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Suite) Reset()         { *m = Suite{} }
func (m *Suite) String() string { return proto.CompactTextString(m) }
func (*Suite) ProtoMessage()    {}
func (*Suite) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3644d9311d3e1fc3, []int{1}
}
func (m *Suite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Suite.Unmarshal(m, b)
}
func (m *Suite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Suite.Marshal(b, m, deterministic)
}
func (dst *Suite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Suite.Merge(dst, src)
}
func (m *Suite) XXX_Size() int {
	return xxx_messageInfo_Suite.Size(m)
}
func (m *Suite) XXX_DiscardUnknown() {
	xxx_messageInfo_Suite.DiscardUnknown(m)
}

var xxx_messageInfo_Suite proto.InternalMessageInfo

func (m *Suite) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Suite) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Suite) GetTests() []*Test {
	if m != nil {
		return m.Tests
	}
	return nil
}

func (m *Suite) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *Suite) GetFinishedAt() int64 {
	if m != nil {
		return m.FinishedAt
	}
	return 0
}

type Test struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	State                Test_State `protobuf:"varint,3,opt,name=state,enum=api.Test_State" json:"state,omitempty"`
	Failure              *Failure   `protobuf:"bytes,4,opt,name=failure" json:"failure,omitempty"`
	StartedAt            int64      `protobuf:"varint,5,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	FinishedAt           int64      `protobuf:"varint,6,opt,name=finished_at,json=finishedAt" json:"finished_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3644d9311d3e1fc3, []int{2}
}
func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (dst *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(dst, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Test) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Test) GetState() Test_State {
	if m != nil {
		return m.State
	}
	return Test_UNKNOWN
}

func (m *Test) GetFailure() *Failure {
	if m != nil {
		return m.Failure
	}
	return nil
}

func (m *Test) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *Test) GetFinishedAt() int64 {
	if m != nil {
		return m.FinishedAt
	}
	return 0
}

type Failure struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Failure) Reset()         { *m = Failure{} }
func (m *Failure) String() string { return proto.CompactTextString(m) }
func (*Failure) ProtoMessage()    {}
func (*Failure) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3644d9311d3e1fc3, []int{3}
}
func (m *Failure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Failure.Unmarshal(m, b)
}
func (m *Failure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Failure.Marshal(b, m, deterministic)
}
func (dst *Failure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Failure.Merge(dst, src)
}
func (m *Failure) XXX_Size() int {
	return xxx_messageInfo_Failure.Size(m)
}
func (m *Failure) XXX_DiscardUnknown() {
	xxx_messageInfo_Failure.DiscardUnknown(m)
}

var xxx_messageInfo_Failure proto.InternalMessageInfo

func (m *Failure) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Failure) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateRequest struct {
	Report               *Report  `protobuf:"bytes,1,opt,name=report" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3644d9311d3e1fc3, []int{4}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetReport() *Report {
	if m != nil {
		return m.Report
	}
	return nil
}

type CreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_3644d9311d3e1fc3, []int{5}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Report)(nil), "api.Report")
	proto.RegisterType((*Suite)(nil), "api.Suite")
	proto.RegisterType((*Test)(nil), "api.Test")
	proto.RegisterType((*Failure)(nil), "api.Failure")
	proto.RegisterType((*CreateRequest)(nil), "api.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "api.CreateResponse")
	proto.RegisterEnum("api.Test_State", Test_State_name, Test_State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Reporter service

type ReporterClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type reporterClient struct {
	cc *grpc.ClientConn
}

func NewReporterClient(cc *grpc.ClientConn) ReporterClient {
	return &reporterClient{cc}
}

func (c *reporterClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/api.Reporter/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Reporter service

type ReporterServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

func RegisterReporterServer(s *grpc.Server, srv ReporterServer) {
	s.RegisterService(&_Reporter_serviceDesc, srv)
}

func _Reporter_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Reporter",
	HandlerType: (*ReporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Reporter_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_api_3644d9311d3e1fc3) }

var fileDescriptor_api_3644d9311d3e1fc3 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xdf, 0x6a, 0xd4, 0x40,
	0x14, 0xc6, 0x9b, 0x7f, 0x93, 0xee, 0x49, 0xbb, 0x0e, 0x23, 0x48, 0x10, 0xa4, 0x4b, 0x44, 0xd9,
	0xab, 0x15, 0xb2, 0xde, 0x4b, 0x68, 0x52, 0x09, 0x5b, 0xd3, 0x90, 0x6c, 0xf5, 0x52, 0x46, 0x77,
	0xaa, 0x03, 0x66, 0x13, 0x33, 0xb3, 0x6f, 0xe1, 0x83, 0x88, 0x4f, 0x29, 0x73, 0x92, 0x08, 0xb5,
	0x17, 0x2e, 0x78, 0x37, 0xe7, 0xfb, 0xce, 0x99, 0xf3, 0xcb, 0xc7, 0x04, 0xce, 0x79, 0x27, 0x5f,
	0xf1, 0x4e, 0xae, 0xba, 0xbe, 0xd5, 0x2d, 0x73, 0x78, 0x27, 0xa3, 0x9f, 0x16, 0x90, 0x4a, 0x74,
	0x6d, 0xaf, 0xd9, 0x1c, 0x6c, 0xb9, 0x0b, 0xad, 0x85, 0xb5, 0x9c, 0x55, 0xb6, 0xdc, 0x31, 0x06,
	0xee, 0x9e, 0x37, 0x22, 0xb4, 0x51, 0xc1, 0x33, 0x7b, 0x02, 0xe4, 0x73, 0xdb, 0x34, 0x52, 0x87,
	0x0e, 0xaa, 0x63, 0xc5, 0x22, 0x20, 0xea, 0x20, 0xb5, 0x50, 0xa1, 0xbb, 0x70, 0x96, 0x41, 0x0c,
	0x2b, 0xb3, 0xa7, 0x36, 0x52, 0x35, 0x3a, 0xec, 0x19, 0x80, 0xd2, 0xbc, 0xd7, 0x62, 0xf7, 0x91,
	0xeb, 0xd0, 0x5b, 0x58, 0x4b, 0xa7, 0x9a, 0x8d, 0x4a, 0xa2, 0xd9, 0x05, 0x04, 0x77, 0x72, 0x2f,
	0xd5, 0xd7, 0xc1, 0x27, 0xe8, 0xc3, 0x24, 0x25, 0x3a, 0xfa, 0x61, 0x81, 0x87, 0x37, 0x1e, 0x45,
	0x7a, 0x01, 0x9e, 0x16, 0x4a, 0xab, 0xd0, 0x41, 0xa0, 0x19, 0x02, 0x6d, 0x85, 0xd2, 0xd5, 0xa0,
	0xff, 0x85, 0xe3, 0xfe, 0x03, 0xc7, 0x7b, 0x80, 0xf3, 0xcb, 0x06, 0xd7, 0xdc, 0x77, 0x14, 0xcd,
	0x0b, 0xf0, 0x94, 0xe6, 0x5a, 0x60, 0x6c, 0xf3, 0xf8, 0xd1, 0x1f, 0x9a, 0x55, 0x6d, 0xe4, 0x6a,
	0x70, 0xd9, 0x4b, 0xf0, 0xef, 0xb8, 0xfc, 0x76, 0xe8, 0x05, 0x02, 0x05, 0xf1, 0x19, 0x36, 0x5e,
	0x0d, 0x5a, 0x35, 0x99, 0xff, 0x1d, 0x65, 0x0b, 0x1e, 0xee, 0x65, 0x01, 0xf8, 0xb7, 0xc5, 0xa6,
	0xb8, 0xf9, 0x50, 0xd0, 0x13, 0x06, 0x40, 0xca, 0xa4, 0xae, 0xb3, 0x94, 0x5a, 0xe6, 0x7c, 0x95,
	0xe4, 0xd7, 0x59, 0x4a, 0x6d, 0xd3, 0x54, 0x6f, 0xf2, 0xb2, 0xcc, 0x52, 0xea, 0x98, 0xa2, 0xcc,
	0x8a, 0x34, 0x2f, 0xde, 0x52, 0x97, 0x9d, 0xc1, 0x69, 0x99, 0x14, 0xf9, 0xe5, 0x26, 0x4b, 0xa9,
	0x67, 0xaa, 0x6d, 0xfe, 0x2e, 0x4b, 0x6f, 0x6e, 0xb7, 0x94, 0x98, 0xc6, 0xbc, 0x78, 0x9f, 0x5c,
	0xe7, 0x29, 0xf5, 0xa3, 0x35, 0xf8, 0xe3, 0x47, 0x3c, 0x88, 0x2b, 0x04, 0xbf, 0x11, 0x4a, 0xf1,
	0x2f, 0x53, 0x62, 0x53, 0x19, 0xbd, 0x86, 0xf3, 0xcb, 0x5e, 0x98, 0x78, 0xc4, 0xf7, 0x83, 0x49,
	0xfa, 0x39, 0x90, 0x1e, 0xdf, 0x2a, 0x8e, 0x07, 0x71, 0x80, 0xe9, 0x0c, 0xcf, 0xb7, 0x1a, 0xad,
	0x88, 0xc2, 0x7c, 0x9a, 0x52, 0x5d, 0xbb, 0x57, 0x22, 0x7e, 0x03, 0xa7, 0x43, 0x8f, 0xe8, 0xd9,
	0x1a, 0xc8, 0xe0, 0x32, 0x86, 0xc3, 0xf7, 0x16, 0x3c, 0x7d, 0x7c, 0x4f, 0x1b, 0xc6, 0xa3, 0x93,
	0x4f, 0x04, 0x7f, 0x98, 0xf5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x0e, 0x56, 0xe0, 0x41,
	0x03, 0x00, 0x00,
}
