// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flake.service.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FlakeListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlakeListRequest) Reset()         { *m = FlakeListRequest{} }
func (m *FlakeListRequest) String() string { return proto.CompactTextString(m) }
func (*FlakeListRequest) ProtoMessage()    {}
func (*FlakeListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_flake_service_ea1766b792e315d5, []int{0}
}
func (m *FlakeListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlakeListRequest.Unmarshal(m, b)
}
func (m *FlakeListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlakeListRequest.Marshal(b, m, deterministic)
}
func (dst *FlakeListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlakeListRequest.Merge(dst, src)
}
func (m *FlakeListRequest) XXX_Size() int {
	return xxx_messageInfo_FlakeListRequest.Size(m)
}
func (m *FlakeListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FlakeListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FlakeListRequest proto.InternalMessageInfo

type FlakeListResponse struct {
	Flakes               []*Flake `protobuf:"bytes,1,rep,name=flakes" json:"flakes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlakeListResponse) Reset()         { *m = FlakeListResponse{} }
func (m *FlakeListResponse) String() string { return proto.CompactTextString(m) }
func (*FlakeListResponse) ProtoMessage()    {}
func (*FlakeListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_flake_service_ea1766b792e315d5, []int{1}
}
func (m *FlakeListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlakeListResponse.Unmarshal(m, b)
}
func (m *FlakeListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlakeListResponse.Marshal(b, m, deterministic)
}
func (dst *FlakeListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlakeListResponse.Merge(dst, src)
}
func (m *FlakeListResponse) XXX_Size() int {
	return xxx_messageInfo_FlakeListResponse.Size(m)
}
func (m *FlakeListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FlakeListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FlakeListResponse proto.InternalMessageInfo

func (m *FlakeListResponse) GetFlakes() []*Flake {
	if m != nil {
		return m.Flakes
	}
	return nil
}

func init() {
	proto.RegisterType((*FlakeListRequest)(nil), "api.FlakeListRequest")
	proto.RegisterType((*FlakeListResponse)(nil), "api.FlakeListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Flaker service

type FlakerClient interface {
	List(ctx context.Context, in *FlakeListRequest, opts ...grpc.CallOption) (*FlakeListResponse, error)
}

type flakerClient struct {
	cc *grpc.ClientConn
}

func NewFlakerClient(cc *grpc.ClientConn) FlakerClient {
	return &flakerClient{cc}
}

func (c *flakerClient) List(ctx context.Context, in *FlakeListRequest, opts ...grpc.CallOption) (*FlakeListResponse, error) {
	out := new(FlakeListResponse)
	err := grpc.Invoke(ctx, "/api.Flaker/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Flaker service

type FlakerServer interface {
	List(context.Context, *FlakeListRequest) (*FlakeListResponse, error)
}

func RegisterFlakerServer(s *grpc.Server, srv FlakerServer) {
	s.RegisterService(&_Flaker_serviceDesc, srv)
}

func _Flaker_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlakeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlakerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flaker/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlakerServer).List(ctx, req.(*FlakeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Flaker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Flaker",
	HandlerType: (*FlakerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Flaker_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flake.service.proto",
}

func init() { proto.RegisterFile("flake.service.proto", fileDescriptor_flake_service_ea1766b792e315d5) }

var fileDescriptor_flake_service_ea1766b792e315d5 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xcb, 0x49, 0xcc,
	0x4e, 0xd5, 0x2b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x4e, 0x2c, 0xc8, 0x94, 0xe2, 0x2e, 0xa9, 0x2c, 0x48, 0x2d, 0x86, 0x88, 0x28, 0x09, 0x71,
	0x09, 0xb8, 0x81, 0x14, 0xfa, 0x64, 0x16, 0x97, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28,
	0x99, 0x73, 0x09, 0x22, 0x89, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x29, 0x71, 0xb1, 0x81,
	0x4d, 0x2c, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0xe2, 0xd2, 0x4b, 0x2c, 0xc8, 0xd4, 0x03,
	0xab, 0x0b, 0x82, 0xca, 0x18, 0x39, 0x72, 0xb1, 0x81, 0x05, 0x8a, 0x84, 0xcc, 0xb9, 0x58, 0x40,
	0xba, 0x85, 0x44, 0x11, 0xaa, 0x90, 0x6c, 0x90, 0x12, 0x43, 0x17, 0x86, 0x58, 0xa2, 0xc4, 0x90,
	0xc4, 0x06, 0x76, 0x96, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x79, 0xd9, 0x9d, 0xac, 0xbf, 0x00,
	0x00, 0x00,
}
