// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reporter.service.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReporterCreateReq struct {
	Report               *Report  `protobuf:"bytes,1,opt,name=report" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReporterCreateReq) Reset()         { *m = ReporterCreateReq{} }
func (m *ReporterCreateReq) String() string { return proto.CompactTextString(m) }
func (*ReporterCreateReq) ProtoMessage()    {}
func (*ReporterCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_service_8216e7946e5f2e27, []int{0}
}
func (m *ReporterCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReporterCreateReq.Unmarshal(m, b)
}
func (m *ReporterCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReporterCreateReq.Marshal(b, m, deterministic)
}
func (dst *ReporterCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReporterCreateReq.Merge(dst, src)
}
func (m *ReporterCreateReq) XXX_Size() int {
	return xxx_messageInfo_ReporterCreateReq.Size(m)
}
func (m *ReporterCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReporterCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReporterCreateReq proto.InternalMessageInfo

func (m *ReporterCreateReq) GetReport() *Report {
	if m != nil {
		return m.Report
	}
	return nil
}

type ReporterCreateRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReporterCreateRes) Reset()         { *m = ReporterCreateRes{} }
func (m *ReporterCreateRes) String() string { return proto.CompactTextString(m) }
func (*ReporterCreateRes) ProtoMessage()    {}
func (*ReporterCreateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_service_8216e7946e5f2e27, []int{1}
}
func (m *ReporterCreateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReporterCreateRes.Unmarshal(m, b)
}
func (m *ReporterCreateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReporterCreateRes.Marshal(b, m, deterministic)
}
func (dst *ReporterCreateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReporterCreateRes.Merge(dst, src)
}
func (m *ReporterCreateRes) XXX_Size() int {
	return xxx_messageInfo_ReporterCreateRes.Size(m)
}
func (m *ReporterCreateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReporterCreateRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReporterCreateRes proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ReporterCreateReq)(nil), "api.ReporterCreateReq")
	proto.RegisterType((*ReporterCreateRes)(nil), "api.ReporterCreateRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Reporter service

type ReporterClient interface {
	Create(ctx context.Context, in *ReporterCreateReq, opts ...grpc.CallOption) (*ReporterCreateRes, error)
}

type reporterClient struct {
	cc *grpc.ClientConn
}

func NewReporterClient(cc *grpc.ClientConn) ReporterClient {
	return &reporterClient{cc}
}

func (c *reporterClient) Create(ctx context.Context, in *ReporterCreateReq, opts ...grpc.CallOption) (*ReporterCreateRes, error) {
	out := new(ReporterCreateRes)
	err := grpc.Invoke(ctx, "/api.Reporter/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Reporter service

type ReporterServer interface {
	Create(context.Context, *ReporterCreateReq) (*ReporterCreateRes, error)
}

func RegisterReporterServer(s *grpc.Server, srv ReporterServer) {
	s.RegisterService(&_Reporter_serviceDesc, srv)
}

func _Reporter_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReporterCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Create(ctx, req.(*ReporterCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Reporter",
	HandlerType: (*ReporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Reporter_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reporter.service.proto",
}

func init() {
	proto.RegisterFile("reporter.service.proto", fileDescriptor_reporter_service_8216e7946e5f2e27)
}

var fileDescriptor_reporter_service_8216e7946e5f2e27 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4a, 0x2d, 0xc8,
	0x2f, 0x2a, 0x49, 0x2d, 0xd2, 0x2b, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x94, 0xe2, 0x2e, 0xa9, 0x2c, 0x48, 0x2d, 0x86, 0x88,
	0x28, 0x59, 0x70, 0x09, 0x06, 0x41, 0xd5, 0x3a, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x06, 0xa5, 0x16,
	0x0a, 0x29, 0x73, 0xb1, 0x41, 0x0c, 0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd6, 0x4b,
	0x2c, 0xc8, 0xd4, 0x83, 0xa8, 0x0b, 0x82, 0x4a, 0x29, 0x09, 0x63, 0xea, 0x2c, 0x36, 0x72, 0xe3,
	0xe2, 0x80, 0x09, 0x0a, 0x59, 0x71, 0xb1, 0x41, 0x24, 0x84, 0xc4, 0x90, 0xf4, 0x23, 0xd9, 0x23,
	0x85, 0x5d, 0xbc, 0x58, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x3a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc0, 0x1f, 0x65, 0xd2, 0xc9, 0x00, 0x00, 0x00,
}
