// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Test_State int32

const (
	Test_UNKNOWN  Test_State = 0
	Test_PASSED   Test_State = 1
	Test_FAILED   Test_State = 2
	Test_SKIPPED  Test_State = 3
	Test_PENDING  Test_State = 4
	Test_PANICKED Test_State = 5
	Test_TIMEDOUT Test_State = 6
	Test_INVALID  Test_State = 7
)

var Test_State_name = map[int32]string{
	0: "UNKNOWN",
	1: "PASSED",
	2: "FAILED",
	3: "SKIPPED",
	4: "PENDING",
	5: "PANICKED",
	6: "TIMEDOUT",
	7: "INVALID",
}
var Test_State_value = map[string]int32{
	"UNKNOWN":  0,
	"PASSED":   1,
	"FAILED":   2,
	"SKIPPED":  3,
	"PENDING":  4,
	"PANICKED": 5,
	"TIMEDOUT": 6,
	"INVALID":  7,
}

func (x Test_State) String() string {
	return proto.EnumName(Test_State_name, int32(x))
}
func (Test_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_3d1577236c0ea4c0, []int{1, 0}
}

type SuiteSummary struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Codebase             string   `protobuf:"bytes,2,opt,name=codebase" json:"codebase,omitempty"`
	Commit               string   `protobuf:"bytes,3,opt,name=commit" json:"commit,omitempty"`
	Tests                []*Test  `protobuf:"bytes,4,rep,name=tests" json:"tests,omitempty"`
	StartedAt            int64    `protobuf:"varint,5,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	FinishedAt           int64    `protobuf:"varint,6,opt,name=finished_at,json=finishedAt" json:"finished_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuiteSummary) Reset()         { *m = SuiteSummary{} }
func (m *SuiteSummary) String() string { return proto.CompactTextString(m) }
func (*SuiteSummary) ProtoMessage()    {}
func (*SuiteSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_3d1577236c0ea4c0, []int{0}
}
func (m *SuiteSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuiteSummary.Unmarshal(m, b)
}
func (m *SuiteSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuiteSummary.Marshal(b, m, deterministic)
}
func (dst *SuiteSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuiteSummary.Merge(dst, src)
}
func (m *SuiteSummary) XXX_Size() int {
	return xxx_messageInfo_SuiteSummary.Size(m)
}
func (m *SuiteSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_SuiteSummary.DiscardUnknown(m)
}

var xxx_messageInfo_SuiteSummary proto.InternalMessageInfo

func (m *SuiteSummary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SuiteSummary) GetCodebase() string {
	if m != nil {
		return m.Codebase
	}
	return ""
}

func (m *SuiteSummary) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *SuiteSummary) GetTests() []*Test {
	if m != nil {
		return m.Tests
	}
	return nil
}

func (m *SuiteSummary) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *SuiteSummary) GetFinishedAt() int64 {
	if m != nil {
		return m.FinishedAt
	}
	return 0
}

type Test struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	State                Test_State `protobuf:"varint,2,opt,name=state,enum=api.Test_State" json:"state,omitempty"`
	Failure              *Failure   `protobuf:"bytes,3,opt,name=failure" json:"failure,omitempty"`
	Location             string     `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	StartedAt            int64      `protobuf:"varint,5,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	FinishedAt           int64      `protobuf:"varint,6,opt,name=finished_at,json=finishedAt" json:"finished_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_3d1577236c0ea4c0, []int{1}
}
func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (dst *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(dst, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Test) GetState() Test_State {
	if m != nil {
		return m.State
	}
	return Test_UNKNOWN
}

func (m *Test) GetFailure() *Failure {
	if m != nil {
		return m.Failure
	}
	return nil
}

func (m *Test) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Test) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *Test) GetFinishedAt() int64 {
	if m != nil {
		return m.FinishedAt
	}
	return 0
}

type Failure struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Failure) Reset()         { *m = Failure{} }
func (m *Failure) String() string { return proto.CompactTextString(m) }
func (*Failure) ProtoMessage()    {}
func (*Failure) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_3d1577236c0ea4c0, []int{2}
}
func (m *Failure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Failure.Unmarshal(m, b)
}
func (m *Failure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Failure.Marshal(b, m, deterministic)
}
func (dst *Failure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Failure.Merge(dst, src)
}
func (m *Failure) XXX_Size() int {
	return xxx_messageInfo_Failure.Size(m)
}
func (m *Failure) XXX_DiscardUnknown() {
	xxx_messageInfo_Failure.DiscardUnknown(m)
}

var xxx_messageInfo_Failure proto.InternalMessageInfo

func (m *Failure) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Flake struct {
	Codebase             string   `protobuf:"bytes,1,opt,name=codebase" json:"codebase,omitempty"`
	Commit               string   `protobuf:"bytes,2,opt,name=commit" json:"commit,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Location             string   `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	Successes            int64    `protobuf:"varint,5,opt,name=successes" json:"successes,omitempty"`
	Failures             int64    `protobuf:"varint,6,opt,name=failures" json:"failures,omitempty"`
	FirstOccurrence      string   `protobuf:"bytes,7,opt,name=first_occurrence,json=firstOccurrence" json:"first_occurrence,omitempty"`
	LastOccurrence       string   `protobuf:"bytes,8,opt,name=last_occurrence,json=lastOccurrence" json:"last_occurrence,omitempty"`
	Failure              *Failure `protobuf:"bytes,9,opt,name=failure" json:"failure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flake) Reset()         { *m = Flake{} }
func (m *Flake) String() string { return proto.CompactTextString(m) }
func (*Flake) ProtoMessage()    {}
func (*Flake) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_3d1577236c0ea4c0, []int{3}
}
func (m *Flake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flake.Unmarshal(m, b)
}
func (m *Flake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flake.Marshal(b, m, deterministic)
}
func (dst *Flake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flake.Merge(dst, src)
}
func (m *Flake) XXX_Size() int {
	return xxx_messageInfo_Flake.Size(m)
}
func (m *Flake) XXX_DiscardUnknown() {
	xxx_messageInfo_Flake.DiscardUnknown(m)
}

var xxx_messageInfo_Flake proto.InternalMessageInfo

func (m *Flake) GetCodebase() string {
	if m != nil {
		return m.Codebase
	}
	return ""
}

func (m *Flake) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *Flake) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Flake) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Flake) GetSuccesses() int64 {
	if m != nil {
		return m.Successes
	}
	return 0
}

func (m *Flake) GetFailures() int64 {
	if m != nil {
		return m.Failures
	}
	return 0
}

func (m *Flake) GetFirstOccurrence() string {
	if m != nil {
		return m.FirstOccurrence
	}
	return ""
}

func (m *Flake) GetLastOccurrence() string {
	if m != nil {
		return m.LastOccurrence
	}
	return ""
}

func (m *Flake) GetFailure() *Failure {
	if m != nil {
		return m.Failure
	}
	return nil
}

func init() {
	proto.RegisterType((*SuiteSummary)(nil), "api.SuiteSummary")
	proto.RegisterType((*Test)(nil), "api.Test")
	proto.RegisterType((*Failure)(nil), "api.Failure")
	proto.RegisterType((*Flake)(nil), "api.Flake")
	proto.RegisterEnum("api.Test_State", Test_State_name, Test_State_value)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_types_3d1577236c0ea4c0) }

var fileDescriptor_types_3d1577236c0ea4c0 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0xc9, 0x7f, 0x73, 0x53, 0x4d, 0x2d, 0x2f, 0x50, 0x84, 0x40, 0x54, 0x45, 0x40, 0xd9,
	0x74, 0x51, 0x9e, 0x20, 0x22, 0x29, 0x8a, 0x3a, 0xa4, 0x51, 0xd2, 0x81, 0xe5, 0xc8, 0x93, 0x71,
	0xc1, 0xa2, 0x69, 0xaa, 0xd8, 0x59, 0xcc, 0xe3, 0xf0, 0x12, 0xf0, 0x7a, 0xc8, 0xce, 0x8f, 0x26,
	0x12, 0x65, 0x33, 0x3b, 0x9f, 0xef, 0x1e, 0x3b, 0xd7, 0xe7, 0x3a, 0xe0, 0x89, 0x87, 0x33, 0xe5,
	0xab, 0x73, 0x5d, 0x89, 0x0a, 0x1b, 0xe4, 0xcc, 0x16, 0x7f, 0x34, 0x98, 0xe6, 0x0d, 0x13, 0x34,
	0x6f, 0xca, 0x92, 0xd4, 0x0f, 0x18, 0x83, 0x79, 0x22, 0x25, 0xf5, 0xb5, 0xb9, 0xb6, 0x74, 0x33,
	0xb5, 0xc6, 0x2f, 0x60, 0x52, 0x54, 0xf7, 0xf4, 0x8e, 0x70, 0xea, 0xeb, 0x8a, 0x0f, 0x1a, 0x3f,
	0x07, 0xbb, 0xa8, 0xca, 0x92, 0x09, 0xdf, 0x50, 0x95, 0x4e, 0xe1, 0xd7, 0x60, 0x09, 0xca, 0x05,
	0xf7, 0xcd, 0xb9, 0xb1, 0xf4, 0xd6, 0xee, 0x8a, 0x9c, 0xd9, 0x6a, 0x4f, 0xb9, 0xc8, 0x5a, 0x8e,
	0x5f, 0x01, 0x70, 0x41, 0x6a, 0x41, 0xef, 0x6f, 0x89, 0xf0, 0xad, 0xb9, 0xb6, 0x34, 0x32, 0xb7,
	0x23, 0x81, 0xdc, 0xef, 0x1d, 0xd8, 0x89, 0xf1, 0x1f, 0x6d, 0xdd, 0x56, 0x75, 0xe8, 0x51, 0x20,
	0x16, 0xbf, 0x75, 0x30, 0xe5, 0x79, 0xff, 0xec, 0xf8, 0x2d, 0x58, 0x5c, 0x10, 0xd1, 0xb6, 0x7b,
	0xb5, 0x9e, 0x0d, 0x5f, 0x5f, 0xe5, 0x12, 0x67, 0x6d, 0x15, 0xbf, 0x03, 0xe7, 0x40, 0xd8, 0xb1,
	0xa9, 0xa9, 0xea, 0xde, 0x5b, 0x4f, 0x95, 0x71, 0xd3, 0xb2, 0xac, 0x2f, 0xca, 0x00, 0x8e, 0x55,
	0x41, 0x04, 0xab, 0x4e, 0xbe, 0xd9, 0x06, 0xd0, 0xeb, 0x27, 0xdf, 0xa3, 0x02, 0x4b, 0xf5, 0x84,
	0x3d, 0x70, 0x6e, 0x92, 0x6d, 0xb2, 0xfb, 0x96, 0xa0, 0x67, 0x18, 0xc0, 0x4e, 0x83, 0x3c, 0x8f,
	0x42, 0xa4, 0xc9, 0xf5, 0x26, 0x88, 0xaf, 0xa3, 0x10, 0xe9, 0xd2, 0x94, 0x6f, 0xe3, 0x34, 0x8d,
	0x42, 0x64, 0x48, 0x91, 0x46, 0x49, 0x18, 0x27, 0x9f, 0x91, 0x89, 0xa7, 0x30, 0x49, 0x83, 0x24,
	0xfe, 0xb4, 0x8d, 0x42, 0x64, 0x49, 0xb5, 0x8f, 0xbf, 0x44, 0xe1, 0xee, 0x66, 0x8f, 0x6c, 0x69,
	0x8c, 0x93, 0xaf, 0xc1, 0x75, 0x1c, 0x22, 0x67, 0xf1, 0x06, 0x9c, 0xee, 0x82, 0xd8, 0x07, 0xa7,
	0xa4, 0x9c, 0x93, 0xef, 0x7d, 0x7a, 0xbd, 0x5c, 0xfc, 0xd2, 0xc1, 0xda, 0x1c, 0xc9, 0xcf, 0xf1,
	0xf0, 0xb5, 0x8b, 0xc3, 0xd7, 0x47, 0xc3, 0xef, 0x47, 0x62, 0x8c, 0x1f, 0xd1, 0xc5, 0x0c, 0x5f,
	0x82, 0xcb, 0x9b, 0xa2, 0xa0, 0x9c, 0x53, 0x3e, 0x44, 0xd8, 0x03, 0xb9, 0xb3, 0x1b, 0x04, 0xef,
	0xf2, 0x1b, 0x34, 0xfe, 0x00, 0xe8, 0xc0, 0x6a, 0x2e, 0x6e, 0xab, 0xa2, 0x68, 0xea, 0x9a, 0x9e,
	0x0a, 0xea, 0x3b, 0xea, 0xf4, 0x99, 0xe2, 0xbb, 0x01, 0xe3, 0xf7, 0x30, 0x3b, 0x92, 0xb1, 0x73,
	0xa2, 0x9c, 0x57, 0x12, 0x3f, 0x32, 0x3e, 0x7a, 0x15, 0xee, 0x7f, 0x5e, 0xc5, 0x9d, 0xad, 0xfe,
	0xa3, 0x8f, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x49, 0x5b, 0x38, 0x6b, 0x56, 0x03, 0x00, 0x00,
}
