// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// State represents possible test states.
type Test_State int32

const (
	Test_UNKNOWN  Test_State = 0
	Test_PASSED   Test_State = 1
	Test_FAILED   Test_State = 2
	Test_SKIPPED  Test_State = 3
	Test_PENDING  Test_State = 4
	Test_PANICKED Test_State = 5
	Test_TIMEDOUT Test_State = 6
	Test_INVALID  Test_State = 7
)

var Test_State_name = map[int32]string{
	0: "UNKNOWN",
	1: "PASSED",
	2: "FAILED",
	3: "SKIPPED",
	4: "PENDING",
	5: "PANICKED",
	6: "TIMEDOUT",
	7: "INVALID",
}
var Test_State_value = map[string]int32{
	"UNKNOWN":  0,
	"PASSED":   1,
	"FAILED":   2,
	"SKIPPED":  3,
	"PENDING":  4,
	"PANICKED": 5,
	"TIMEDOUT": 6,
	"INVALID":  7,
}

func (x Test_State) String() string {
	return proto.EnumName(Test_State_name, int32(x))
}
func (Test_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_68bcf2e3ea18d2c9, []int{1, 0}
}

// A Report represents the result of a test suite run.
type Report struct {
	// description is the suite description, e.g. "Integration Suite".
	Description string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	// import_path is the suite's project's import path, e.g. "github.com/teddyking/snowflake".
	ImportPath string `protobuf:"bytes,2,opt,name=import_path,json=importPath" json:"import_path,omitempty"`
	// commit is the current git commit of the codebase on which the suite was run.
	Commit string `protobuf:"bytes,3,opt,name=commit" json:"commit,omitempty"`
	// tests are the suite's test results.
	Tests []*Test `protobuf:"bytes,4,rep,name=tests" json:"tests,omitempty"`
	// started_at is the time at which the test suite started.
	StartedAt int64 `protobuf:"varint,5,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	// finished_at is the time at which the test suite finished.
	FinishedAt           int64    `protobuf:"varint,6,opt,name=finished_at,json=finishedAt" json:"finished_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_68bcf2e3ea18d2c9, []int{0}
}
func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (dst *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(dst, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Report) GetImportPath() string {
	if m != nil {
		return m.ImportPath
	}
	return ""
}

func (m *Report) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *Report) GetTests() []*Test {
	if m != nil {
		return m.Tests
	}
	return nil
}

func (m *Report) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *Report) GetFinishedAt() int64 {
	if m != nil {
		return m.FinishedAt
	}
	return 0
}

// A Test represents the result of a test run.
type Test struct {
	// description is the test description, e.g. "Handler returns an HTTP 200".
	Description string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	// state is the resulting state of the test run.
	State Test_State `protobuf:"varint,2,opt,name=state,enum=api.Test_State" json:"state,omitempty"`
	// failure represents a test failure and is only set if state == FAILED.
	Failure *Failure `protobuf:"bytes,3,opt,name=failure" json:"failure,omitempty"`
	// location is the filepath:linenumber for the test.
	Location string `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	// started_at is the time at which the test started.
	StartedAt int64 `protobuf:"varint,5,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	// finished_at is the time at which the test finished.
	FinishedAt           int64    `protobuf:"varint,6,opt,name=finished_at,json=finishedAt" json:"finished_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_68bcf2e3ea18d2c9, []int{1}
}
func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (dst *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(dst, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Test) GetState() Test_State {
	if m != nil {
		return m.State
	}
	return Test_UNKNOWN
}

func (m *Test) GetFailure() *Failure {
	if m != nil {
		return m.Failure
	}
	return nil
}

func (m *Test) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Test) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *Test) GetFinishedAt() int64 {
	if m != nil {
		return m.FinishedAt
	}
	return 0
}

// A Failure represents a test failure.
type Failure struct {
	// message is the output from the failing test, e.g. "expected A to equal B".
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Failure) Reset()         { *m = Failure{} }
func (m *Failure) String() string { return proto.CompactTextString(m) }
func (*Failure) ProtoMessage()    {}
func (*Failure) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_68bcf2e3ea18d2c9, []int{2}
}
func (m *Failure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Failure.Unmarshal(m, b)
}
func (m *Failure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Failure.Marshal(b, m, deterministic)
}
func (dst *Failure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Failure.Merge(dst, src)
}
func (m *Failure) XXX_Size() int {
	return xxx_messageInfo_Failure.Size(m)
}
func (m *Failure) XXX_DiscardUnknown() {
	xxx_messageInfo_Failure.DiscardUnknown(m)
}

var xxx_messageInfo_Failure proto.InternalMessageInfo

func (m *Failure) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// A Flake represents a flaking test, one that has both a PASSED and FAILED
// state.
type Flake struct {
	// import_path is the suite's project's import path, e.g. "github.com/teddyking/snowflake".
	ImportPath string `protobuf:"bytes,1,opt,name=import_path,json=importPath" json:"import_path,omitempty"`
	// commit is the current git commit of the codebase on which the suite was run.
	Commit string `protobuf:"bytes,2,opt,name=commit" json:"commit,omitempty"`
	// suite_description is the test's suite's description, e.g. "Integration Suite".
	SuiteDescription string `protobuf:"bytes,3,opt,name=suite_description,json=suiteDescription" json:"suite_description,omitempty"`
	// test_description is the test description, e.g. "Handler returns an HTTP 200".
	TestDescription string `protobuf:"bytes,4,opt,name=test_description,json=testDescription" json:"test_description,omitempty"`
	// location is the filepath:linenumber for the test.
	Location string `protobuf:"bytes,5,opt,name=location" json:"location,omitempty"`
	// successes is the number of times the test completed with a PASSED state.
	Successes int64 `protobuf:"varint,6,opt,name=successes" json:"successes,omitempty"`
	// failures is the number of times the test completed with a FAILED state.
	Failures int64 `protobuf:"varint,7,opt,name=failures" json:"failures,omitempty"`
	// started_at is the time at which the test first started flaking.
	StartedAt int64 `protobuf:"varint,8,opt,name=started_at,json=startedAt" json:"started_at,omitempty"`
	// failure contains information about why the test is sometimes failing.
	Failure              *Failure `protobuf:"bytes,9,opt,name=failure" json:"failure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flake) Reset()         { *m = Flake{} }
func (m *Flake) String() string { return proto.CompactTextString(m) }
func (*Flake) ProtoMessage()    {}
func (*Flake) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_68bcf2e3ea18d2c9, []int{3}
}
func (m *Flake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flake.Unmarshal(m, b)
}
func (m *Flake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flake.Marshal(b, m, deterministic)
}
func (dst *Flake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flake.Merge(dst, src)
}
func (m *Flake) XXX_Size() int {
	return xxx_messageInfo_Flake.Size(m)
}
func (m *Flake) XXX_DiscardUnknown() {
	xxx_messageInfo_Flake.DiscardUnknown(m)
}

var xxx_messageInfo_Flake proto.InternalMessageInfo

func (m *Flake) GetImportPath() string {
	if m != nil {
		return m.ImportPath
	}
	return ""
}

func (m *Flake) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *Flake) GetSuiteDescription() string {
	if m != nil {
		return m.SuiteDescription
	}
	return ""
}

func (m *Flake) GetTestDescription() string {
	if m != nil {
		return m.TestDescription
	}
	return ""
}

func (m *Flake) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Flake) GetSuccesses() int64 {
	if m != nil {
		return m.Successes
	}
	return 0
}

func (m *Flake) GetFailures() int64 {
	if m != nil {
		return m.Failures
	}
	return 0
}

func (m *Flake) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *Flake) GetFailure() *Failure {
	if m != nil {
		return m.Failure
	}
	return nil
}

func init() {
	proto.RegisterType((*Report)(nil), "api.Report")
	proto.RegisterType((*Test)(nil), "api.Test")
	proto.RegisterType((*Failure)(nil), "api.Failure")
	proto.RegisterType((*Flake)(nil), "api.Flake")
	proto.RegisterEnum("api.Test_State", Test_State_name, Test_State_value)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_types_68bcf2e3ea18d2c9) }

var fileDescriptor_types_68bcf2e3ea18d2c9 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x26, 0x49, 0x93, 0x34, 0x27, 0x13, 0x33, 0xbe, 0x40, 0x11, 0x02, 0xad, 0x2a, 0x02, 0x15,
	0x21, 0xf5, 0xa2, 0x3c, 0x41, 0x84, 0x53, 0x14, 0x75, 0x64, 0x51, 0xda, 0xc1, 0x65, 0x65, 0x32,
	0x8f, 0x5a, 0xb4, 0x4b, 0x14, 0x9f, 0x5e, 0xf0, 0x60, 0xbc, 0xc1, 0x1e, 0x0c, 0xd9, 0x49, 0x4b,
	0xd6, 0x8b, 0x09, 0x69, 0x77, 0xfd, 0x7e, 0x5c, 0xfb, 0x9c, 0xef, 0x0b, 0x84, 0xf8, 0xbb, 0x16,
	0x6a, 0x5a, 0x37, 0x15, 0x56, 0xd4, 0xe1, 0xb5, 0x1c, 0xdf, 0x5b, 0xe0, 0x15, 0xa2, 0xae, 0x1a,
	0xa4, 0x23, 0x08, 0x6f, 0x84, 0x2a, 0x1b, 0x59, 0xa3, 0xac, 0xee, 0x22, 0x6b, 0x64, 0x4d, 0x82,
	0xa2, 0x4f, 0xd1, 0x0b, 0x08, 0xe5, 0x4e, 0x7b, 0xd7, 0x35, 0xc7, 0x4d, 0x64, 0x1b, 0x07, 0xb4,
	0x54, 0xce, 0x71, 0x43, 0x5f, 0x82, 0x57, 0x56, 0xbb, 0x9d, 0xc4, 0xc8, 0x31, 0x5a, 0x87, 0xe8,
	0x05, 0xb8, 0x28, 0x14, 0xaa, 0x68, 0x30, 0x72, 0x26, 0xe1, 0x2c, 0x98, 0xf2, 0x5a, 0x4e, 0x57,
	0x42, 0x61, 0xd1, 0xf2, 0xf4, 0x0d, 0x80, 0x42, 0xde, 0xa0, 0xb8, 0x59, 0x73, 0x8c, 0xdc, 0x91,
	0x35, 0x71, 0x8a, 0xa0, 0x63, 0x62, 0x7d, 0x3e, 0xbc, 0x95, 0x77, 0x52, 0x6d, 0x5a, 0xdd, 0x33,
	0x3a, 0x1c, 0xa8, 0x18, 0xc7, 0xf7, 0x36, 0x0c, 0xf4, 0xff, 0xfd, 0xc7, 0x10, 0xef, 0xc0, 0x55,
	0xc8, 0x51, 0x98, 0xe7, 0x3f, 0x9f, 0x9d, 0x1f, 0xdf, 0x32, 0x5d, 0x6a, 0xba, 0x68, 0x55, 0xfa,
	0x1e, 0xfc, 0x5b, 0x2e, 0xb7, 0xfb, 0x46, 0x98, 0x59, 0xc2, 0xd9, 0x99, 0x31, 0xce, 0x5b, 0xae,
	0x38, 0x88, 0xf4, 0x15, 0x0c, 0xb7, 0x55, 0xc9, 0xcd, 0x6d, 0x03, 0x73, 0xdb, 0x11, 0x3f, 0x79,
	0xaa, 0x0a, 0x5c, 0xf3, 0x26, 0x1a, 0x82, 0x7f, 0x9d, 0x2d, 0xb2, 0xab, 0xef, 0x19, 0x79, 0x46,
	0x01, 0xbc, 0x3c, 0x5e, 0x2e, 0x13, 0x46, 0x2c, 0xfd, 0x7b, 0x1e, 0xa7, 0x97, 0x09, 0x23, 0xb6,
	0x36, 0x2d, 0x17, 0x69, 0x9e, 0x27, 0x8c, 0x38, 0x1a, 0xe4, 0x49, 0xc6, 0xd2, 0xec, 0x0b, 0x19,
	0xd0, 0x33, 0x18, 0xe6, 0x71, 0x96, 0x7e, 0x5e, 0x24, 0x8c, 0xb8, 0x1a, 0xad, 0xd2, 0xaf, 0x09,
	0xbb, 0xba, 0x5e, 0x11, 0x4f, 0x1b, 0xd3, 0xec, 0x5b, 0x7c, 0x99, 0x32, 0xe2, 0x8f, 0xdf, 0x82,
	0xdf, 0x0d, 0x48, 0x23, 0xf0, 0x77, 0x42, 0x29, 0xfe, 0x53, 0x74, 0x4b, 0x3c, 0xc0, 0xf1, 0x1f,
	0x1b, 0xdc, 0xf9, 0x96, 0xff, 0x12, 0xa7, 0x7d, 0xb0, 0x1e, 0xe9, 0x83, 0xfd, 0xa0, 0x0f, 0x1f,
	0xe1, 0x85, 0xda, 0x4b, 0x14, 0xeb, 0x7e, 0x56, 0x6d, 0x65, 0x88, 0x11, 0x58, 0x2f, 0xb0, 0x0f,
	0x40, 0x74, 0x49, 0x1e, 0x78, 0xdb, 0x4d, 0x9f, 0x6b, 0xbe, 0x6f, 0xed, 0x87, 0xe1, 0x9e, 0x84,
	0xf1, 0x1a, 0x02, 0xb5, 0x2f, 0x4b, 0xa1, 0x94, 0x50, 0xdd, 0xae, 0xff, 0x11, 0xfa, 0x64, 0x97,
	0xa8, 0x8a, 0x7c, 0x23, 0x1e, 0xf1, 0x49, 0x8c, 0xc3, 0xd3, 0x18, 0x7b, 0x4d, 0x09, 0x1e, 0x69,
	0xca, 0x0f, 0xcf, 0x7c, 0x76, 0x9f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xda, 0x02, 0xd9,
	0x85, 0x03, 0x00, 0x00,
}
